export const database = {
  name: "Sarah Ayu Nanda",
  role: "Frontend Developer",
  headline: "Frontend Developer building thoughtful web products",
  location: "Yogyakarta, Indonesia",
  email: "nanda.sarahayu@gmail.com",
  phone: "+62 813-2848-4322",
  profiles: [
    "https://www.linkedin.com/in/sarahayunanda/",
    "https://github.com/SarahAyuNanda",
    "https://medium.com/@sarah.bugdeveloper",
  ],
  skills: [
    "Git",
    "Javascript",
    "TypeScript",
    "Kotlin",
    "Android Studio",
    "Go",
    "Python",
    "Vite",
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "React Native",
    "Tailwind CSS",
    "Shadcn UI",
    "NuxtUI",
    "Material UI",
    "Bootstrap",
    "Ant Design",
    "Semantic UI",
    "Tanstack Query",
    "Strapi CMS",
    "Docker",
    "Vercel",
    "Claude",
  ],
  projects: [
    {
      title: "Portfolio CMS",
      period: "2026",
      summary:
        "A headless CMS-driven portfolio starter with dynamic content blocks and SEO-first pages.",
      stack: ["Next.js", "TypeScript", "Tailwind"],
      link: "https://github.com/",
    },
  ],
} as const;
